--- 
- hosts: linuxhosts
  become: true
  tasks:
    - name: install nginx on ubuntu
      apt: name=nginx state=absent
      when: ansible_os_family == "Debian"

    - name: install nginx on centos
      yum: name=nginx state=absent
      when: ansible_os_family == "Redat"