--- 
- name: Playbook with variables demo
  hosts: linuxhosts
  var:
    - var1: zig
    - var2: zag
  task:
    - name: print data 
      shell: echo "{{var1}} when you should {{var2}}" > /home/devasc/Desktop/vars.txt