--- 
- hosts: linuxhosts
  become: true
  tasks:
    - name: install nginx on ubuntu
      apt: name=nginx state=latest
      # This will generate an error on CentOS
      ignore_errors: yes
      # when it fails, want to store the failure in a variable
      # for next task to run in case of failure
      register: resuls

    - name: install nginx on centos
      yum: name=nginx state=latest
      when: results|failed